M48
; DRILL file {KiCad (6.0.1)} date Wed Feb  9 22:26:22 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-09T22:26:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.2834Y-3.2579
X4.0789Y-1.4018
X5.5373Y-6.5725
X6.9957Y-1.4018
X7.7912Y-3.2579
T0
M30
